FROM debian:jessie
MAINTAINER Christian Grabowski
ADD https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz /opt/bin/go1.6.2.linux-amd64.tar.gz
RUN mkdir -p /opt/go/src/github.com/cpg1111/maestrod/ && tar -C /usr/local/ -xzvf /opt/bin/go1.6.2.linux-amd64.tar.gz
ADD . /opt/go/src/github.com/cpg1111/maestrod/container/
ENV GOPATH /opt/go/
ENV PATH $PATH:/usr/local/go/bin/
WORKDIR /opt/go/src/github.com/cpg1111/maestrod/container/
RUN go build
ENTRYPOINT ["./container"]

# FOR BUILDING CONTAINER BINARY ONLY!!!!
