FROM golang:1.8
MAINTAINER Christian Grabowski
COPY . /go/src/github.com/cpg1111/maestrod/
RUN apt-get update --fix-missing && apt-get install -y build-essential curl && \
    curl https://glide.sh/get | sh
ENV PATH $PATH:/usr/local/go/bin/:$GOPATH/bin/
WORKDIR $GOPATH/src/github.com/cpg1111/maestrod/
ENTRYPOINT ["./build.sh"]
