FROM golang:1.6
MAINTAINER Christian Grabowski
ADD . /go/src/github.com/cpg1111/maestrod/
RUN apt-get update --fix-missing && apt-get install -y build-essential git cmake pkg-config wget unzip
ENV PATH $PATH:/usr/local/go/bin/:$GOPATH/bin/
WORKDIR $GOPATH/src/github.com/cpg1111/maestrod/
ENTRYPOINT ["make"]
