[Server]
Runtime="docker"
RuntimePluginPath="/etc/maestrod/plugin.d/docker"
RuntimeTLSClient=true
RuntimeTLSServer=true
MaxBuilds=6
DataStoreType="redis"
DataStoreUser=""
DataStorePWD=""
DataStoreEnvIP="ETCD_SERVICE_HOST"
DataStoreEnvPort="ETCD_SERVICE_PORT"
TargetProtocol="https"
TargetHost=""
TargetPort=""
TargetEnvHost="KUBERNETES_SERVICE_HOST"
TargetEnvPort="KUBERNETES_SERVICE_PORT"
MaestroVersion="0.1.1"
ClientCertPath="/etc/maestrod/clientcrt.pem"
ClientKeyPath="/etc/maestrod/clientkey.pem"
ServerCertPath="/etc/maestrod/fullchain.pem"
ServerKeyPath="/etc/maestrod/privkey.pem"
Host="0.0.0.0"
SecurePort=8484
InsecurePort=8585
WorkspaceDir="/tmp/"

[[Projects]]
Name="cpg1111/maestrod"
MaestroConfPath="../maestro/test_conf.toml"
DeployBranches=["master"]
