all: build
get-deps:
	cd $(GOPATH)
	go get github.com/kardianos/govendor
build:
	govendor sync
	go build -o maestrod-container container/main.go
	go build -o maestrod main.go
test:
	ETCD2_SERVICE_HOST=127.0.0.1 ETCD2_SERVICE_PORT=22380 go test ./datastore/etcd/v2/...
	ETCD3_SERVICE_HOST=127.0.0.1 ETCD3_SERVICE_PORT=32380 go test ./datastore/etcd/v3/...
	MONGO_SERVICE_HOST=127.0.0.1 MONGO_SERVICE_PORT=27017 go test ./datastore/mongodb/...
	REDIS_SERVICE_HOST-127.0.0.1 REDIS_SERVICE_PORT=6379 go test ./datastore/redis/...
	go test ./config/...
	go test ./lifecycle/...
	go test ./manager/docker/...
	go test ./manager/k8s/...
install:
	mkdir -p /opt/bin/maestrod
	mkdir -p /etc/maestrod/
	cp maestrod-container /opt/bin/maestrod/maestrod-container
	cp maestrod /opt/bin/maestrod/maestrod
	cp example.conf.toml /etc/maestrod/conf.toml
